### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by seananderson** [fate-spatialindicators/non-stationary#1]
- [x] hot spot map - Sean
- [x] AR1 trial - Sean
- [x] simulate AR1 and without (add in to the sim function) - Eric
- [x] plot eps. for all species (quadrant / hot spot idea) - Sean
- [x] where try north south index - Lewis
- [x] show simulation test - Eric
- [x] center time predictor - Sean
- [x] cross-validation
- [ ] qq plot by year, with focus on first and last years. Use the new posterior samples to generate these - Eric, Lewis 
- [ ] sum up Sean's spatial maps to better visualize differences (avg latitude, etc). Generate summary statistics based on the estimated spatiotemporal fields
- [x] include example(s) of EBS (P cod)- Lewis
- [x] fit models with spatial field and AR1 spatiotemporal 
- [ ] revise 2x2 map figure (current fig 3)
- [x] simulation-based indices- Lewis
- [x] spatial + AR1 fits (w PC priors?) - Lewis

- [ ] dig in a bit into weird fits
- [ ] look into the slope coefs for 4-5 of interesting ones
- [ ] look at AR1 correlation for ones where the mean is changing - is that it?
- [ ] something on quality of fits: 
- [x] MVN residuals - Sean
- [ ] table on how papers have dealt with time and spatial non-stationarity (Christian?)

Main figs:
1. motivation: residual trends
2. simulated illustration of how trend estimation depends on observation error, distribution family, etc.
3. estimated coefficients for all species
4. index trends for all species
5. hot spots map or mean-centered epsilon_st for lingcod or other species with large magnitude trend
